name: CI

on: [push]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v4

      - name: ⏬ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: ⏬ Install
        run: |
          npm install

      - name: ✨ Lint
        run: |
          npm run lint

      - name: 🔨 Build
        run: |
          npm run build

      - name: 🧪 Test
        run: |
          npm test
        env:
          FORCE_COLOR: 1

      - name: 📦 Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages
          FOLDER: dist
          single-commit: true
